---
# Executa o comando DENTRO do sistema recém-instalado (chroot)
dontChroot: false

# Tempo limite em segundos
timeout: 30

# Mensagem exibida na interface do Calamares durante a execução
i18n:
    name: "Configurando repositórios..."

# O comando que injeta os repositórios corretamente
script:
    - "sed -i -E 's/ main.*/ main contrib non-free non-free-firmware/g' /etc/apt/sources.list"
